language: scala
scala:
  - 3.0.0
before_deploy:
  - sbt deployScript
deploy:
  provider: pages:git
  edge: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master